# Use Debian-based Python image
FROM python:3.8-slim-buster

# Install build essentials and Python dev package
RUN apt-get update && apt-get install -y build-essential python3-dev

# Install SSH client
RUN apt-get update && apt-get install -y openssh-client

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the requirements.txt file and install Python dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy your application files into the container
COPY . /usr/src/app/

# Expose the port the app runs on
EXPOSE 8501

# Command to run the app
CMD ["streamlit", "run", "app.py"]
